### PR TITLE
improve translation in other language

### PR DESCRIPTION
**Pull request by valentin-p**
Hi
I created an helper to manage translation of the tags in the app.
Tell me if anything need to be modified before a merge.
Have a good day
Valentin

### CODE REVIEW

**Comment by RickCarlino** [comment]
This looks great @valentin-p . I will take a look now.

**Comment by RickCarlino** [comment]
@valentin-p I made a small change to your script:

```
// Need to run this cmd in this folder: node _helper.js fr
var language = process.argv[2];
HelperNamespace.createOrUpdateTranslationFile(language);
```

The script can take command line arguments such as `node _helper.js fr` now.

This is a great tool - it's going to be a great help for other translators!

**Comment by elenderg** [comment]
Maybe it's time to update the README file?

**Comment by RickCarlino** [comment]
Sure. Will fix it up later today.

**Comment by valentin-p** [comment]
No problem for the improvement.
You can take the French translation file as well.

**Pull request merged**
